services:
  server:
    container_name: challenge-it-patagonia
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c 'until nc -z -v -w30 db 3306; do echo "Waiting for DB..."; sleep 5; done; npm install && npx sequelize-cli db:migrate --config src/database/config/config.sequelize.js --migrations-path src/database/migrations && npm run start'
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: challenge-it-patatonia
    ports:
      - "33066:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Simonelo40787935?
      MYSQL_DATABASE: companies_db
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
